num_threads=8
tree_learner=serial

task=train
num_iterations=100
learning_rate=0.1
num_leaves=255

min_data_in_leaf=1
min_sum_hessian_in_leaf=100

max_bin=64
is_sparse=false
two_round=true

metric=ndcg
ndcg_at=1,3,5,10

enable_bundle=true
max_conflict_rate=0
