num_thread=8

# Benchmark-specific parameters
task=train
tree_learner=serial
objective=lambdarank
num_iterations=100
learning_rate=0.1
num_leaves=255
min_data_in_leaf=1
min_sum_hessian_in_leaf=100
max_bin=64

# Evaluate ndcg@1, ndcg@5, ndcg@10
metric=ndcg
ndcg_at=1,5,10

# EFB with gamma=0
enable_bundle=true
max_conflict_rate=0
