num_thread=8

task=train
tree_learner=serial
max_bin=255
num_leaves=255
num_iterations=100
learning_rate=0.1
min_data_in_leaf=1
min_sum_hessian_in_leaf=100

# Enable GOSS
boosting=goss
top_rate=0.05
other_rate=0.05

# Enable EFB
enable_bundle=true
max_conflict_rate=0
